---
abstract: 'Transparent interface to Math::GMPq, Math::GMPz, Math::MPFR and Math::MPC.'
author:
  - 'Daniel Șuteu <trizenx@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-AnyNum
provides:
  Math::AnyNum:
    file: lib/Math/AnyNum.pm
    version: '0.01'
requires:
  Class::Multimethods: '1.7'
  Math::GMPq: '0.41'
  Math::GMPz: '0.39'
  Math::MPC: '1.07'
  Math::MPFR: '3.29'
  POSIX: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
